<a href="https://colab.research.google.com/github/lancasjo/Pytorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Basics**

***DO NOT EDIT THIS SCRIPT***

***CREATE A COPY AND EDIT IN YOUR PERSONAL CODE FOLDER***

PyTorch is an open-source machine learning library for Python, based on Torch, used for applications such deep learning and computer vision. It is known for its ability to perform dynamic computation graphs and its use of tensors, similar to numpy arrays, which make it easy to perform mathematical operations. PyTorch also provides support for CUDA, which allows for efficient parallel processing on GPUs.

In [ ]:
import torch
import numpy as np

Tensors: PyTorch uses tensors, similar to numpy arrays, to perform mathematical operations. You can create a tensor by passing a list or array to the torch.Tensor() function. For example:

In [ ]:
# Create a 1-D tensor
tensor_1d = torch.Tensor([1, 2, 3])
print(f'Tensor 1d:\n{tensor_1d}\n')

# Create a 2-D tensor
tensor_2d = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(f'Tensor 2d:\n{tensor_2d}\n')

# Create a tensor from a numpy array
numpy_3d = np.random.randint(0, 100, (2, 3, 4))
tensor_3d = torch.Tensor(numpy_3d)
print(f'Tensor 3d:\n{tensor_3d}\n')

Tensor 1d:
tensor([1., 2., 3.])

Tensor 2d:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Tensor 3d:
tensor([[[39.,  9., 82., 35.],
         [20., 58., 82.,  8.],
         [92., 71., 26., 33.]],

        [[37., 97.,  4., 76.],
         [47., 14., 20., 17.],
         [74.,  9., 24., 94.]]])



Shape: Printing the shape of a tensor can be useful in a variety of situations, such as: 

1. Debugging: When working with large and complex tensors, it can be useful to print the shape to ensure that the tensor has the expected dimensions. This can help identify errors, such as transposed matrices or missing dimensions.
2. Understanding data: The shape of a tensor can provide information about the structure of the data, such as the number of samples and features. This can be useful for understanding the data and making sure it is in the correct format for a specific task.
3. Model design: The shape of the tensors in a model can be used to ensure that the model is properly designed and that the dimensions match between the layers.

Here is an example:

In [ ]:
# Print shape of 1-D tensor
shape_1d = tensor_1d.shape
print(f'Shape 1d:\n{shape_1d}\n')

# Print shape of 2-D tensor
shape_2d = tensor_2d.shape
print(f'Shape 2d:\n{shape_2d}\n')

# Print shape of 3-D tensor
shape_3d = tensor_3d.shape
print(f'Shape 3d:\n{shape_3d}\n')

Shape 1d:
torch.Size([3])

Shape 2d:
torch.Size([2, 3])

Shape 3d:
torch.Size([2, 3, 4])



Operations: You can perform various mathematical operations on tensors, such as addition, multiplication, and matrix multiplication. Here is an example:

In [ ]:
# Addition
result = tensor_1d + tensor_1d
print(f'tensor_1d + tensor_1d:\n{result}\n')

# Multiplication
result = tensor_1d * tensor_1d
print(f'tensor_1d * tensor_1d:\n{result}\n')

# Matrix multiplication
result = torch.matmul(tensor_2d, tensor_2d.T)
print(f'tensor_2d @ tensor_2d.T:\n{result}\n')
print(f'tensor_2d shape : {tensor_2d.shape}\ntensor_2d.T shape : {tensor_2d.T.shape}\nresult shape : {result.shape}')

tensor_1d + tensor_1d:
tensor([2., 4., 6.])

tensor_1d * tensor_1d:
tensor([1., 4., 9.])

tensor_2d @ tensor_2d.T:
tensor([[14., 32.],
        [32., 77.]])

tensor_2d shape : torch.Size([2, 3])
tensor_2d.T shape : torch.Size([3, 2])
result shape : torch.Size([2, 2])


Cuda: PyTorch makes it easy to compute operations using the GPU. This helps with speed, as GPUs are designed to perform parallel computations, which can lead to a significant speedup in the training of machine learning models. It also helps with memor and power. Here is an example comparing the time it takes to perform an operation on the cpu and the time it takes to do it on the GPU:

In [ ]:
import time

#Check if you have cuda available
if torch.cuda.is_available():
  print('You have the GPU available!\n')
  device = 'cuda:0'
else:
  print("Could not find GPU! If you want to enable GPU, go to Edit > Notebook Settings > Hardware Accelerator and select GPU.\n\nIt is possible that you are out of colab allowed GPU units")
  device = 'cpu'

if torch.cuda.is_available():

  # Create a large tensor, setting the tensor be on the cpu
  x = torch.rand(10000, 10000, device='cpu')

  # Perform a computation on the CPU
  start_time = time.time()
  y = x.matmul(x)
  print(f'CPU computation time: {time.time() - start_time}\n')

  # Move the tensor to the GPU
  x = x.to("cuda")

  # Perform the same computation on the GPU
  start_time = time.time()
  y = x.matmul(x)
  print(f'GPU computation 1st time: {time.time() - start_time}\n')

  # After starting to use the GPU, it gets much faster after 'warming up'
  start_time = time.time()
  y = x.matmul(x)
  print(f'GPU computation 2nd time: {time.time() - start_time}\n')

You have the GPU available!

CPU computation time: 15.430630683898926

GPU computation 1st time: 0.00030159950256347656

GPU computation 2nd time: 0.001135110855102539



Gradients: PyTorch also allows you to calculate gradients, which is useful for training machine learning models. You can enable gradients on a tensor by setting the requires_grad attribute to True. Here is an example:

In [ ]:
# Create a tensor with requires_grad set to True
x = torch.tensor([3.0], requires_grad=True)

# Perform a computation
y = x ** 2

# Compute the gradients
y.backward()

# Print the gradients
gradient = x.grad
print(f'Gradient of y=x^2 at x=3:\n{gradient}')

Gradient of y=x^2 at x=3:
tensor([6.])


Using what you now learned, try to solve this problem:

##Problem

You are given a 3-dimensional tensor called data of shape (10, 3, 2) representing 10 samples, each with 3 features and 2 values. Your task is to compute the mean and standard deviation of the values for each feature.

##What you should do

1. Compute the mean of the values for each feature using PyTorch functions.
2. Compute the standard deviation of the values for each feature using PyTorch functions.
3. Print the mean and standard deviation of the values for each feature.

##Note

You should research what torch functions can help you find the mean and standard deviation. PyTorch has great documentation!

In [ ]:
# Create a 3-dimensional tensor of data
data = torch.randn((10, 3, 2), device=device)

# Compute the mean of the values for each feature


# Compute the standard deviation of the values for each feature


# Print the mean and standard deviation of the values for each feature

